name: Close Issue on Commit

on:
  push:
    branches:
      - main

jobs:
  close-issue-on-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up API token
        env:
          API_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: echo "Setting up API token"
        
      - name: Close Issue
        id: close_issue
        run: |
          # Gets the list of commit messages
          COMMIT_MESSAGES=$(git log --pretty=%B -n 1 ${{ github.sha }})
          echo $COMMIT_MESSAGES
          done
