name: Close Issue on Commit

on:
  push:
    branches:
      - main
    pull_request_target:
      types:
        - closed
    schedule:
      - cron: '0 */4 * * *'
  
jobs:
  lock:
    runs-on: ubuntu-latest
    
    permissions:
      issues: write

    steps:
      - name: Close Issue Action
        uses: peter-evans/close-issue@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: robson-cruz/forest_insight
          close-reason: completed

      - name: Close Issue
        id: close_issue
        run: |
          # Gets the list of commit messages
          COMMIT_MESSAGES=$(git log --pretty=%B)
          echo $COMMIT_MESSAGES
          
          # Search for issue numbers in the commit message
          ISSUE_NUMBERS=$(echo "$COMMIT_MESSAGES" | grep -oE '#[0-9]+' | grep -oE '[0-9]+')
        
          # Closes issues found in commits
          for ISSUE_NUMBER in $ISSUE_NUMBERS; do
            echo "Closing issue #$ISSUE_NUMBER"
            # Verifies if the issue number is empty
            if [ -z "$ISSUE_NUMBER" ]; then
              echo "Empty issue number. Skipping."
              continue
            fi
          
            # Close issues
            # Close the issue using the issue number
            gh issue close "robson-cruz/forest_insight" --issue $ISSUE_NUMBER --reason "completed"
          done
