name: Close Issue on Commit

on:
  push:
    branches:
      - main		
    pull_request_target:
      types:
        - closed
    schedule:
      - cron: '0 */4 * * *'
  
jobs:
  close_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Close Issue
        id: close_issue
        run: |
          # Extrai o número da issue da mensagem de commit
          ISSUE_NUMBER=$(git log --pretty=%B | grep -oE '#[0-9]+' | grep -oE '[0-9]+' | head -n 1)
          
          # Verifica se o número da issue está vazio
          if [ -z "$ISSUE_NUMBER" ]; then
            echo "Nenhum número de issue encontrado na mensagem do commit. Não é possível fechar a issue."
            exit 1
          fi
          
          # Fecha a issue usando o número da issue
          gh issue close "robson-cruz/forest_insight" --issue $ISSUE_NUMBER --reason "completed"
