name: Close Issue on Commit

on:
  issues:
    state: open

permissions:
  issues: write
  
jobs:
  lock:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: OSDKDev/lock-issues@v1.1 #actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up API token
        env:
          API_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: echo "Setting up API token"

      - name: Close Issue
        id: close_issue
        run: |
          # Gets the list of commit messages
          COMMIT_MESSAGES=$(git log --pretty=%B)
          # Search for issue numbers in the commit message
          ISSUE_NUMBERS=$(echo "$COMMIT_MESSAGES" | grep -oE '#[0-9]+' | grep -oE '[0-9]+')
          # Closes issues found in commits
          for ISSUE_NUMBER in $ISSUE_NUMBERS; do
            echo "Fechando issue #$ISSUE_NUMBER"
            # Verifica se o número da issue está vazio
            if [ -z "$ISSUE_NUMBER" ]; then
              echo "Número de issue vazio. Ignorando."
              continue
            fi
            # Tenta fechar a issue
            RESPONSE=$(curl -L \
              -X PUT \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $API_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/lock \
              -d '{"lock_reason":"resolved"}')
              
            # Verifica o código de resposta
            if [ "$RESPONSE" -eq "204" ]; then
              echo "Issue #$ISSUE_NUMBER fechada com sucesso."
            else
              echo "Falha ao fechar a issue #$ISSUE_NUMBER. Código de resposta: $RESPONSE"
            fi
          done
