name: Close Issue on Commit

on:
  push:
    branches:
      - main
    pull_request_target:
      types:
        - closed
    schedule:
      - cron: '0 */4 * * *'
  
jobs:
  lock:
    runs-on: ubuntu-latest
    
    permissions:
      issues: write
    
    steps:
      - name: Close Issue
        id: close_issue
        run: |
          # Gets the list of commit messages
          COMMIT_MESSAGES=$(git log --pretty=%B)
        
          # Search for issue numbers in the commit message
          ISSUE_NUMBERS=$(echo "$COMMIT_MESSAGES" | grep -oE '#[0-9]+' | grep -oE '[0-9]+')
        
          # Closes issues found in commits
          for ISSUE_NUMBER in $ISSUE_NUMBERS; do
            echo "Fechando issue #$ISSUE_NUMBER"
            # Verifica se o número da issue está vazio
            if [ -z "$ISSUE_NUMBER" ]; then
              echo "Número de issue vazio. Ignorando."
              continue
            fi
          
            # Close issues
            curl -X PATCH\
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
              -H "Content-Type: application/json" \
              https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/lock \
              -d '{"state":"closed"}'

             # Optionally, add labels after closing the issue
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
              -H "Content-Type: application/json" \
              https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/labels \
              -d '{"labels":["✔️"]}'
          done
