name: Close Issue on Commit

on:
  schedule:
    - cron: '0 */4 * * *'
  
jobs:
  lock:
    runs-on: ubuntu-latest
    
    permissions:
      issues: write
    
    steps:
      - name: User and Token
        uses: peter-evans/close-issue@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          issue-lock-comment: "hello! :wave:\n\nThis issue is being automatically closed because it was solved."
          closed-issues-label: "✔️"

      - name: Close Issue
        id: close_issue
        run: |
          # Gets the list of commit messages
          COMMIT_MESSAGES=$(git log --pretty=%B)
        
          # Search for issue numbers in the commit message
          ISSUE_NUMBERS=$(echo "$COMMIT_MESSAGES" | grep -oE '#[0-9]+' | grep -oE '[0-9]+')
        
          # Closes issues found in commits
          for ISSUE_NUMBER in $ISSUE_NUMBERS; do
            echo "Fechando issue #$ISSUE_NUMBER"
            # Verifica se o número da issue está vazio
            if [ -z "$ISSUE_NUMBER" ]; then
              echo "Número de issue vazio. Ignorando."
              continue
            fi
          
            # Fechar issues
            curl -L \
              -X PUT \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/lock \
              -d "{\"state_reason\":\"$(echo -n "${{ secrets.issue-lock-comment }}")\"}"
          done
